# Generated by Django 6.1.1 on 2026-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='new', related_name='posts', to='blog.tag'),
        ),
    ]
